PreserveThreading=true
[mattermost]
    [mattermost.betagouv]
    Server="${MATTERMOST_BETAGOUV_SERVER}"
    Team="${MATTERMOST_BETAGOUV_TEAM}"
    Login="${MATTERMOST_BETAGOUV_BOT_LOGIN}"
    Password="${MATTERMOST_BETAGOUV_BOT_PASSWORD}"
    PrefixMessagesWithNick=true
    RemoteNickFormat="[{PROTOCOL}] <{NICK}> "
    [mattermost.alumni]
    Server="${MATTERMOST_BETAGOUV_SERVER}"
    Team="${MATTERMOST_BETAGOUV_ALUMNI_TEAM}"
    Login="${MATTERMOST_BETAGOUV_BOT_LOGIN}"
    Password="${MATTERMOST_BETAGOUV_BOT_PASSWORD}"
    PrefixMessagesWithNick=true
    RemoteNickFormat="[{PROTOCOL}] <{NICK}> "

[slack]
    [slack.betagouv]
    Token="${SLACK_BETAGOUV_TOKEN}"
    PrefixMessagesWithNick=true
    RemoteNickFormat="[On parle ici -> https://mattermost.incubateur.net et de l'aide sur #aide-mattermost] <{NICK}> "

[[samechannelgateway]]
    enable = true
    name = "samechannel1"
    accounts = [ "mattermost.betagouv","mattermost.alumni" ]
    channels = [ "domaine-dev", "tmp-lucas-test" ]
